name = "orange-meets"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-10-07"
main = "./build/index.js"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "meet.carlosguerrero.com", custom_domain = true },
  { pattern = "meet.omattic.com", custom_domain = true },
  { pattern = "meet.inglesconliza.com", custom_domain = true }
]

[site]
  bucket = "./public"

[vars]
CALLS_APP_ID = "339e4152dc107967bb1ea1ec7d7f469d"

[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

# Indicate that you want the ChatRoom class to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom"]

# The necessary secrets are:
# - CALLS_APP_SECRET
# To add secret, run `echo <VALUE> | wrangler secret put <NAME>`
